### ISSUE TITLE
Problem when copying/creating of large file takes a long time

### ISSUE THREAD

**Issue by alex-ander-is** [bevry/watchr#100] opened 2017-12-17 11:43 UTC
During creating/copying a huge file from another source, error was fired.
Please note, the process of copying large file takes some time.

_When copying started, watchr detected creation of new file with no problems:_
`"create" dropbox/A.mkv`

_Then, during copying process, alert was fired:_
`**(node:54305) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 done listeners added. Use emitter.setMaxListeners() to increase limit**`

_Once copying process finished, update event was fired properly:_
`"update" dropbox/A.mkv`

**Comment by balupton** [comment] 2023-11-24 14:11
dupe of #97

**Closed by balupton** 2023-11-24 14:11 UTC
